version: "3"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: logmeindb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: logmeindb
      DB_USER: postgres
      DB_PASSWORD: postgres
    # Expose le port 5000 sur ta machine (localhost:5000 -> container:5000)
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
