version: "3"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: logmeindb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: cedricteyc/littlepigs-backend:latest
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: logmeindb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: cedricteyc/littlepigs-frontend:latest
    restart: always

  nginx:
    image: cedricteyc/littlepigs-nginx:latest
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: