name: MAJ automatique planifiée backend

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: docker build -t local-backend:latest ./backend

      - name: Message de succès
        if: success()
        run: echo "✅ Build réussi : les mises à jour hebdomadaires du backend se sont bien passées !"

      - name: Message d’échec
        if: failure()
        run: |
          echo "❌ Build échoué : une mise à jour a cassé le build du backend."
          echo "Pour diagnostiquer :"
          echo "1️⃣ Va dans l’onglet 'Actions' de ton repo GitHub."
          echo "2️⃣ Sélectionne 'MAJ automatique planifiée backend'."
          echo "3️⃣ Clique sur la dernière exécution échouée pour voir le détail des logs."
          echo "Corrige l’erreur puis relance le workflow si besoin."
