name: Cluster Healthcheck

on:
  workflow_dispatch:   # déclenchement manuel dans l’UI GitHub Actions

jobs:
  healthcheck:
    name: Cluster Healthcheck & Logs
    runs-on: self-hosted
    env:
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_IP: ${{ secrets.ADMIN_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Copier healthcheck.sh et cluster_config.yml sur admin-auto
        run: |
          scp -o StrictHostKeyChecking=no scripts/healthcheck.sh $ADMIN_USER@$ADMIN_IP:~/
          scp -o StrictHostKeyChecking=no cluster_config.yml $ADMIN_USER@$ADMIN_IP:~/

      - name: Exécuter le healthcheck (logs + checks)
        run: |
          ssh -o StrictHostKeyChecking=no $ADMIN_USER@$ADMIN_IP "chmod +x ~/healthcheck.sh && ~/healthcheck.sh"

      - name: Récupérer et afficher le log du check
        run: |
          scp -o StrictHostKeyChecking=no $ADMIN_USER@$ADMIN_IP:~/cluster_health.log ./cluster_health.log
          cat ./cluster_health.log
